library(phyloseq)
library(plyr)
library(ggplot2)
library(data.table)
setwd("~/Google Drive/virome2/corrected/signif-subset")

abund <- read.delim(sep='\t', file="./abund.subset.txt",header=TRUE, strip.white=TRUE, row.names=1)

cluster <-read.delim(sep='\t', file="./cluster.txt",header=FALSE, strip.white=TRUE, row.names=1)
colnames(cluster) <- c("g")
cluster <- data.frame(cluster)
cluster$g <- as.character(cluster$g)
bcd <- vegdist(abund, method="bray")
#bcd<-vegdist(foo, method="bray")
clust <- hclust(bcd, method="average")
plot(clust)
adonis(bcd ~ g,cluster)
adonis(bcd ~ g,data=cluster,perm=9999)
groups <- cluster$g
mod <- betadisper(bcd, groups)
anova(mod)
permutest(mod, pairwise = TRUE, permutations=9999)
(mod.HSD <- TukeyHSD(mod))

cluster1 <-read.delim(sep='\t', file="./cluster2.txt",header=FALSE, strip.white=TRUE, row.names=1)
colnames(cluster1) <- c("g1")
cluster1$g1 <- as.character(cluster1$g1)
cluster1 <- data.frame(cluster1)
bcd1 <- vegdist(abund, method="bray")
#bcd<-vegdist(foo, method="bray")
clust1 <- hclust(bcd1, method="average")
plot(clust)
adonis(bcd1 ~ g1,data=cluster1,perm=9999)
groups <- cluster1$g1
mod1 <- betadisper(bcd1, groups)
anova(mod1)
permutest(mod1, pairwise = TRUE, permutations=9999)
(mod1.HSD <- TukeyHSD(mod1))

identical(bcd, bcd1)
